#!/usr/bin/php
<?php
chdir(dirname(__FILE__));
if(!isset($argv[1])){
	die("You must provide a filename.\nUsage: segment_count filename.txt\n");
}

// get the command line argument
$filename=$argv[1];
if(substr($filename,-3)!='.gz'){
	die("You must feed me gzips\n");	
}
echo "Filename $filename\n";



// make and array
$results=array();

// open a gzip file
$handle = gzopen("$filename", 'r');

// read a gzip line by line
while (!gzeof($handle)) {
	$line = gzgets($handle, 4096);
	//echo the line

	// replace some text
	$line=str_replace(":0", "", $line);
	$line=str_replace("\n", "", $line);

	// explode a string
	$line_array=explode("\t", $line);

	// a loop :(
	for($i=1;$i<count($line_array);$i++){
		$results[$line_array[$i]]=$results[$line_array[$i]]+1;
	}
}
gzclose($handle);

//sort the array to get segments in alphabetical
ksort($results);

// print a fine looking sexy table

// clever printing
$mask = "|%-20.20s |%-20.20s|\n";
printf($mask, ' Segment ID ', ' Count ');
printf($mask, '--------------------', '--------------------');
foreach ($results as $key => $value){
	printf($mask, $key, number_format($value));
}

?>